### ISSUE TITLE
Bug or missing code!?

### ISSUE THREAD

**Issue by lamnvo** [YeloPartyHat/LocalDatabase#1]
With your example, when we refresh the page, the database is wiped out and then recreated: All records are lost.

Deleting a record or records based on some predicate is not working. I read your code (LocalDatabase.all.js), in function delete(table, query), you just leave a comment: "Initiate delete", but no more code to do deletion after that!? I don't know much about javascript, so I am not sure I did something wrong or your deleting function is not completed?

IndexedDB also has Cursor. It would be great if you can add operations with cursor.

Besides deletion, I tested all functions provided and they worked great as intended.

Thanks for all your hardwork.

Best regards,

Lam

**Comment by LiamPerson** [comment]
Nice catch. It appears LocalDatabase.delete was not fully implemented there. Must have forgot to commit the code or something! It is fixed now in the latest commit https://github.com/YeloPartyHat/LocalDatabase/commit/88697fae27975368f80fabe533a012289f2786eb

As for the cursor, feel free to add that as a request. I must warn though, I do not have any plans to implement it as it doesn't seem too different from manually iterating with a `for of` loop.
